# Generated by Django 4.2.2 on 2023-06-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spoj",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="solution_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="spoj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.spoj",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("name", "spoj")},
        ),
        migrations.RemoveField(
            model_name="task",
            name="source",
        ),
        migrations.RemoveField(
            model_name="task",
            name="task_content",
        ),
    ]
