# Generated by Django 4.2.2 on 2023-06-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_spoj_task_solution_url_alter_task_id_alter_task_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="spoj",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="tasks.spoj"
            ),
        ),
    ]
