# Generated by Django 4.2.2 on 2023-06-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="spoj",
            name="amount_of_difficulty_levels",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
