# Generated by Django 4.2.2 on 2023-06-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_spoj_amount_of_difficulty_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="difficulty",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
