# Generated by Django 4.2.2 on 2023-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_task_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="difficulty",
            field=models.PositiveIntegerField(),
        ),
    ]
