# Generated by Django 4.2.2 on 2023-06-09 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_alter_task_difficulty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("title", "spoj")},
        ),
    ]
