# Generated by Django 4.2.2 on 2023-06-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_rename_name_task_title_alter_task_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertask",
            name="finished_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="user_note",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="user_solution",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
