# Generated by Django 4.2.2 on 2023-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_alter_usertask_finished_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spoj",
            name="url",
            field=models.URLField(default="https://www.google.pl"),
        ),
    ]
