# Generated by Django 4.2.2 on 2023-06-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_remove_spoj_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="spoj",
            name="url",
            field=models.URLField(default="https://www.google.pl"),
            preserve_default=False,
        ),
    ]
