# Generated by Django 4.2.2 on 2023-06-15 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0013_spoj_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertask",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="usertask",
            unique_together={("task_id", "user_id")},
        ),
    ]
