# Generated by Django 4.2.2 on 2023-06-15 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0014_alter_usertask_id_alter_usertask_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("difficulty", "title", "spoj", "url", "solution_url")},
        ),
    ]
